### PR TITLE
 C ares

### PR DESCRIPTION
**Pull request by gbour**
Hi,

This patch propose to add c-ares library as an alternative to libresolv for DNS resolution.
It is the choice of the user to choose one or other library when running ./configure

Regards,

### CODE REVIEW

**Comment by dirwiz** [comment]
Is there a chance to get c-ares support in libstrophe?  It would be very helpful for mingw builds since libresolv is not supported over there.

**Comment by pasis** [comment]
I will look at it. I didn't want to add support of external lib since we have base lib support for nix systems (libresolv) and native windows implementation (which in a bad condition though). But if you say you have use-case where these both ways don't work, I'll try to add optional support for c-ares.

**Comment by dirwiz** [comment]
I didn't know there was a windows implementation!  By adding c-ares you may not need to have cygwin support.  I've built libcurl with c-ares in mingw without the need for any cygwin libs.  GREAT LIB!  It's nice to see a pure C lib...

**Comment by pasis** [comment]
I've added c-ares support in a13847d9949f05920f94768495872807ae49c773. Thanks for the original patch.

**Comment by gbour** [comment]
thanks very much @pasis

**Pull request closed without merging**
