### PR TITLE
autoconf fixes for Free- and OpenBSD

### PR DESCRIPTION
**Pull request by sizeofvoid**

### CODE REVIEW

**Comment by sizeofvoid** [comment]
Simple modifications to generate a clean configure file for Free- and OpenBSD.

**Comment by Aversiste** [comment]
Works for me on OpenBSD/loongson.

**Comment by pasis** [comment]
Why does BSD require linking with pthread?

**Comment by Aversiste** [comment]
Linking against libpthread is required since src/thread.c exports symbol from it. However, none of the functions are in use today. Is there any plan to expand and use them ? If not it is perhaps better to remove it entirely.

**Comment by pasis** [comment]
I thought src/thread.[ch] are not included in Makefile.am. I don't know the original purpose of those functions and only can guess that author wanted to write parallel version of libstrophe.

Proper solution should be removing thread.[ch] from the Makefile.am

**Comment by sizeofvoid** [comment]
I prefer to  remove thread.[ch] from the Makefile.am after review

**Comment by pasis** [comment]
> Is the rest of the request okay for you?

So my final thoughts:
 * Remove 2 commits with libpthread from PR
 * Remove thread.[ch] from Makefile.am instead of those 2 commits. You can remove whitespaces as part of this commit
 * Make libresolv check as we discussed above
 * Commit @9ff7887 is good, but remove braces `{}` around variables please

Thanks.

**Comment by pasis** [comment]
All features merged/implemented in master. Closing this ticket.

**Pull request closed without merging**
