### PR TITLE
TCP keepalive setting support

### PR DESCRIPTION
**Pull request by stanson-ch**
I made a new pull request on TCP keepalive setting support from new branch, looks better. :)

### CODE REVIEW

**Comment by pasis** [comment]
This code doesn't compile on QNX, because SOL_TCP and TCP_XXX ain't defined. I've found documentation describing keepalive timing for this system: http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.neutrino_lib_ref%2Fg%2Fgetsockopt.html&cp=13_4_10_69&anchor=Keepalive

I'd suggest to leave default value for systems that don't have SOL_TCP:
```
#ifdef SOL_TCP
    if (optval) {
...
    }
#endif /* SOL_TCP */
#endif /* _WIN32 */
```

**Comment by stanson-ch** [comment]
May be something like
`    if (optval) {
#ifdef SOL_TCP
... /* Linux code */
#endif /* SOL_TCP */
#ifdef TCP_KEEPALIVE /* QNX */
    {
... /* QNX code from example */
    }
#endif /* TCP_KEEPALIVE */
    }
#endif /* _WIN32 */
`
I don't have QNX to check, but it seems that there is nothing hard to make it work as expected.
Really, changing only default 7200 seconds idle value will be enough to make the whole thing working, so QNX code can be reduced to
`{
struct timeval tval;
tval.tv_sec = timeout;
tval.tv_usec = 0; /* do we need this for QNX? */
setsockopt(fdi, IPPROTO_TCP, TCP_KEEPALIVE, (void *) &tval, sizeof(tval);
}`
to keep things as simple as possible.

What about *BSD's ? Didn't play much with them.

**Comment by pasis** [comment]
General idea is good, but try to keep such code short. Many ifdef's can make code complex and increase chance of errors.

Please, look at the next comments.

`tval.tv_usec = 0; /* do we need this for QNX? */`
Yes. `tval` allocated on stack and not initialized. If you needed to set 1.5sec interval this structure would look like:
```
tval.tv_sec = 1;
tval.tv_usec = 500000;
```

```
#endif /* SOL_TCP */
#ifdef TCP_KEEPALIVE /* QNX */
```
The above part should be replaced with `#elif defined(TCP_KEEPALIVE)`, because potentially both SOL_TCP and TCP_KEEPALIVE can be defined.

I'm not expert in QNX, but I don't want libstrophe to be broken where it works now. If you have doubts you can leave default value for it. The idea is to bring your new interface, because API needs to be frozen after the next release.
I don't have BSD system at the moment, so I'll check when I setup it.

**Comment by stanson-ch** [comment]
> The above part should be replaced with `#elif defined(TCP_KEEPALIVE)`, because potentially both SOL_TCP and TCP_KEEPALIVE can be defined.

Indeed. Or, it may be better to use some OS-dependent defines like _WIN32 _LINUX _QNX etc.

> I'm not expert in QNX, but I don't want libstrophe to be broken where it works now.

TCP keepalive can't break anything working now, because it is a new function, and there are no changes in other libstrophe functions at all. So, if some software does not use this function, this software will definitely work as expected.

**Comment by pasis** [comment]
> Or, it may be better to use some OS-dependent defines like _WIN32 _LINUX _QNX etc.
I would not recommend this for now.

> TCP keepalive can't break anything working now
I meant compilation errors like it was with QNX.

**Comment by pasis** [comment]
Merged (see @6c1c2a86f85316333fd7766b35660e13a96dd4f7). I fixed code for osx, but I'm confused: qnx manuals describe argument for TCP_KEEPALIVE as `struct timeval`, but osx examples send `int` there (osx manuals don't say anything about type).

**Pull request closed without merging**
