### PR TITLE
Auto-format code

### PR DESCRIPTION
**Pull request by sjaeckel**
In this patch an astyle configuration has been added and all sources were re-formatted.

Please feel free to give feedback on the chosen style, I tried to do the least possible modifications from the current style.

I've tried astyle and clang-format and none of the both could do the following `type *func(const foo * const arg);`.
Both modified this into either `type *func(const foo *const arg);` or (the style I chose now) `type * func(const foo * const arg);`

While discussing this beforehand with @pasis he had one major request

> The only concern regarding auto-format is that sometimes there are special cases when author wants to highlight some logic or make a block more readable with reasonable formatting.

You can do that, as shown in `sha1.c`, via code-comments `/* clang-format off */` resp. `/* clang-format on */`

To be able to spot actual differences in the patch you should really enable the "Hide whitespace changes" option in the diff view.

### CODE REVIEW

**Comment by pasis** [comment]
@sjaeckel , As I'm aware, there are few public forks of libstrophe:
* https://github.com/profanity-im/libmesode
* https://github.com/netxms/netxms (includes libstrophe in src/)
* https://github.com/EpicGames/UnrealEngine (includes libstrophe-0.9.1 in Engine/Source/ThirdParty/libstrophe/)

All other alive public projects use libstrophe as external library. Few words about the above projects:

* libmesode - adds features to openssl module related to certificates, but removes much code. This project mostly merges libstrophe releases and is not developed feature-wise. Every merging phase is a hell and keeping libstrophe untouched won't help here. Better to re-implement certificate features in a good way in libstrophe and don't waste time for backporting libstrophe releases there.

* NetXMS - includes libstrophe with small fixes that are required for their build system and building it on exotic OSes. I backported most fixes from the project already, so updating to newer libstrophe version won't be an issue there.

* UnrealEngine - includes libstrophe as is, no issues here at all.

@vit1251, I would prefer libstrophe to keep developing. And improving quality of the codebase is a right direction to me. If you know some closed forks or have your own which will have issues with this patch, lets discuss options.

@sjaeckel I will check new changes and come back to you.

**Comment by vit1251** [comment]
@pasis no idea how to help you with support keep development. I say that your behavior "close way", "burn bridge" and etc. I can suggest some idea or point to architecture problem but it outdate information I no more use libstrophe.

**Comment by sjaeckel** [comment]
> * libmesode

I just had a look and created the following patch https://github.com/sjaeckel/libstrophe/tree/include-libmesode-api-changes

IIUC that should be all!?

I changed some minor things in the API like `char*` are now `const char*` and I've replaced the modified `xmpp_connect_client()` API, but have a look at the commit message, it should explain what is different.

After this PR is merged we can start discussing that one, probably also with @boothj5 and how we can improve the newly provided API.

> * NetXMS

probably @2128506 would be willing to make a PR with the remaining differences?

> * UnrealEngine - includes libstrophe as is, no issues here at all.

perfect :)

**Comment by pasis** [comment]
> I just had a look and created the following patch https://github.com/sjaeckel/libstrophe/tree/include-libmesode-api-changes

@sjaeckel, Yes,  this is the difference between libstrophe and libmesode.  The only thing is that we need to think carefully how to implement this behaviour properly (API-wise). Also, there are multiple TLS modules besides the openssl. There is a reason why the code wasn't merged into libstrophe :).

Regarding clang-format configuration. I will read the documentation, but for now, few comments:
* `AllowShortIfStatementsOnASingleLine` should be prohibited (I didn't see option for allowing only empty blocks here).
* `AllowShortFunctionsOnASingleLine` - `Empty`, can be helpful for a list of stubs
* `AllowShortBlocksOnASingleLine` - `Empty`
* `BinPackArguments` and `BinPackParameters` are too strict, shouldn't be true
* `ColumnLimit` 80 is better, this is optimal value for console-based editors with 2 columns on 13" and 15" laptops. Bigger number will affect such users. Also, we shouldn't pack multiple lines too aggressively. In first turn, code should be readable for humans :).

I will play with clang-format configuration later. I would like to reduce the number of patched lines.

**Comment by sjaeckel** [comment]
> Yes, this is the difference between libstrophe and libmesode. The only thing is that we need to think carefully how to implement this behaviour properly (API-wise). 

definitely!

> Also, there are multiple TLS modules besides the openssl. There is a reason why the code wasn't merged into libstrophe :).

I'm currently looking into the gnutls part but don't get it yet how to extract those certificate values in gnutls... Probably @nmav has the time to quickly look into it, that'll be solved a lot faster then ;-)

> Regarding clang-format configuration...

sure, feel free to modify the config as you like! I gave you push access to my fork so you can add those changes to the PR.

**Comment by sjaeckel** [comment]
I've applied the changes to `_clang-format` as proposed, reset the sources to the state on master and re-formatted everything

**Comment by pasis** [comment]
Finally I built clang on my Virtualbox/Gentoo and started playing with clang-format. One issue so far: need to format all sources, not only `libstrophe_la_SOURCES`. Current patch doesn't include `src/tls_*` and `src/parser_libxml2`. I used `git ls-files` command to format all the sources, but it won't work with tarballs outside the git repository.

**Comment by pasis** [comment]
@sjaeckel , I'm planning to merge this PR (with changes) after 0.9.3 release. So the patch will be for the next major release.

**Comment by sjaeckel** [comment]
> I'm planning to merge this PR (with changes)

fine by me!

> after 0.9.3 release

do you already have a plan when this will be?

**Comment by pasis** [comment]
> do you already have a plan when this will be?

@sjaeckel, as soon as I have time to review all commits and think what still should be done in 0.9.3.

I think about testing #116, need to create a testing program. Besides this, master is pretty ready for the release.

**Comment by Neustradamus** [comment]
@pasis: Have you planned to add the @sjaeckel code in a release before Christmas 2019?

It is really the missing feature in libstrophe: https://github.com/strophe/libstrophe/issues/133
I am very happy to see this improvement.

And of course, same missing part in strophejs: https://github.com/strophe/strophejs/issues/314
Hope a devel soon...

**Comment by pasis** [comment]
@Neustradamus, I will try to find time to check and merge SCRAM-SHA-256 (without -PLUS). Let's do it before merging current PR.

**Comment by Neustradamus** [comment]
@pasis: @sjaeckel waits it because he will create a new PR to enable all SCRAM possibilities.

**Comment by pasis** [comment]
Pushed changes to branch for now: https://github.com/strophe/libstrophe/tree/reformat-code

**Comment by sjaeckel** [comment]
is it ready now?

**Comment by pasis** [comment]
@sjaeckel , yes, patch is ready. I'm backporting changes from netxms and unrealengine before landing.

**Comment by pasis** [comment]
Integrated into master. Thank you for your contribution!

**Pull request closed without merging**
