### PR TITLE
TLS improvements

### LINKED ISSUE #100: Disabled SSL certificate verify
Hi developers:
    Nowadays we made a large scale security static analysis on several open source projects, and found some mistakes in libstrophe-0.8.8. In the @src/Tls_openssl.c:68:
   tls_t *tls_new(xmpp_ctx_t *ctx, sock_t sock)
  {
     tls_t *tls = xmpp_alloc(ctx, sizeof(*tls));

    if (tls) {
        int ret;
        memset(tls, 0, sizeof(*tls));

        tls->ctx = ctx;
        tls->sock = sock;
        tls->ssl_ctx = SSL_CTX_new(SSLv23_client_method());

       SSL_CTX_set_client_cert_cb(tls->ssl_ctx, NULL);
       SSL_CTX_set_mode (tls->ssl_ctx, SSL_MODE_ENABLE_PARTIAL_WRITE);
       SSL_CTX_set_verify (tls->ssl_ctx, SSL_VERIFY_NONE, NULL);

      tls->ssl = SSL_new(tls->ssl_ctx);
 [..]
}

  The parameter SSL_VERIFY_NONE here can not configure this built-in certificate validation,so the handshake can continue even the cert is invalid.We recommand you use SSL_VERIFY_PEER to guarantee the security.We have send the bug report to Ubuntu launchpad,and also inform you of such news.Here are the link:
https://bugs.launchpad.net/ubuntu/+source/libstrophe/+bug/1677511

### PR DESCRIPTION
**Pull request by labdsf**
Fixes #100 

Please don't squash commits.

### CODE REVIEW

**Comment by pasis** [comment]
Build failed because new functions appeared only in openssl-1.0.2. We can't break build for openssl-1.0.1, because many systems still run it.

v1.0.2-related code can be wrapped with `#if OPENSSL_VERSION_NUMBER > XXX`. See [link](https://wiki.openssl.org/index.php/Manual:OPENSSL_VERSION_NUMBER(3)) for details.

For v1.0.1 we should leave the old code.

**Comment by labdsf** [comment]
Ok, I just disabled verification for 1.0.1.
There is no point adding manual verification for outdated versions of OpenSSL, 1.0.1 is not supported since 2016-12-31. Outdated systems are not going to update libstrophe anyway.

**Comment by pasis** [comment]
Looks fine now. Let me check it with openssl-1.0.2 and then I'll merge.

**Comment by pasis** [comment]
Merged.

**Comment by labdsf** [comment]
I tested it with valid and invalid cert by the way.

**Comment by pasis** [comment]
Nice, thank you.

**Pull request merged**
