### PR TITLE
Add missing headers to resolver.c

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by pasis** [comment]
@jubalh , please, move includes under `#ifdef HAVE_CARES`, because `select()` is used only for c-ares implementation. In `select(2)` manual I see:
```
       /* According to POSIX.1-2001, POSIX.1-2008 */
       #include <sys/select.h>

       /* According to earlier standards */
       #include <sys/time.h>
       #include <sys/types.h>
       #include <unistd.h>
```
So `<time.h>` is not needed as far as I understand. Please, use those 3 includes for earlier standards for non-windows platforms.

**Comment by jubalh** [comment]
@pasis I probably won't have time the next week. Could you do the changes to my PR?

**Comment by pasis** [comment]
@jubalh ok will do.

**Comment by pasis** [comment]
I've pushed modified patch to the master.

**Pull request closed without merging**
